#pragma once
#include "version.h"

#define FILETYPE_TTM 1
#define FILETYPE_CAM 2
#define FILETYPE_TMV 3
#define FILETYPE_REC 4
#define FILETYPE_ALL 5
#define FILETYPE_EXE 6

#define MENU_OPTIONS 10
#define MENU_PROXY 11
#define MENU_GAMEMASTER 12
#define MENU_TOPMOST 13
#define MENU_REGISTER 14
#define MENU_AUTOPLAY 15
#define MENU_DONATE 16
#define MENU_VERSION 17
#define MENU_HOST 18

#define MENU_DELETE_SELECTED 19
#define MENU_DELETE_ALL 20
#define MENU_REMOVE 21
#define MENU_PORT 22
#define MENU_CUSTOM 23

#define LABEL_NO_VIDEO 30
#define LABEL_TOTAL_TIME 31
#define LABEL_WAITING 32
#define LABEL_RECORDING 33
#define LABEL_PLAYING 34
#define LABEL_PAUSED 35
#define LABEL_SLOW 36
#define LABEL_FAST 37
#define LABEL_OVERRIDE 38

#define BUTTON_OPEN 40
#define BUTTON_SAVE 41
#define BUTTON_START 42
#define BUTTON_CANCEL 43
#define BUTTON_STOP 44
#define BUTTON_PAUSE 45
#define BUTTON_PLAY 46
#define BUTTON_RESTART 47

#define TITLE_OPEN_VIDEO 70
#define TITLE_SAVE_VIDEO 71
#define TITLE_START_TIBIA 72
#define TITLE_SELECT_TIBIA 73
#define TITLE_LOADER 74
#define TITLE_LOADER_OVERRIDE 75
#define TITLE_LOADER_ERROR 87
#define TITLE_PROXY 77

#define LABEL_VERSION 80
#define LABEL_HOST 81
#define LABEL_GLOBAL 82
#define LABEL_PORT 83

#define TOOLTIP_VERSION 90
#define TOOLTIP_VERSION_EXPLANATION 91
#define TOOLTIP_HOST 92
#define TOOLTIP_HOST_EXPLANATION 93
#define TOOLTIP_PORT 94
#define TOOLTIP_PORT_EXPLANATION 95

#define PLAY_VIDEO 99

#define ERROR_INVALID_VERSION 100
#define ERROR_INVALID_HOST 101
#define ERROR_INVALID_PORT 102
#define ERROR_CMDLINE 103
#define ERROR_FILE_NOT_EXISTS 104
#define ERROR_URL 105
#define ERROR_VIDEO_FORMAT_NOT_SUPPORTED 106
#define ERROR_CANNOT_APPEND 107
#define ERROR_CANNOT_OPEN_VIDEO_FILE 108
#define ERROR_CANNOT_SAVE_VIDEO_FILE 109
#define ERROR_CORRUPT_VIDEO 110
#define ERROR_TIBICAM_VERSION 111
#define ERROR_UNSUPPORTED_VERSION 112
#define ERROR_WRONG_VERSION 113
#define ERROR_WRONG_HOST 114
#define ERROR_UNSUPPORTED_TIBIA_VERSION 115
#define ERROR_WRONG_TIBIA_EXE 116
#define ERROR_WRONG_TIBIA_VER 117
#define ERROR_WRONG_TIBIA_DIR 118
#define ERROR_WRONG_TIBIA_DAT 119
#define ERROR_WRONG_TIBIA_SPR 120
#define ERROR_WRONG_TIBIA_PIC 121
#define ERROR_START_TIBIA 122
#define ERROR_START_SERVERS 123
#define ERROR_GET_BASE_ADDRESS 124
#define ERROR_CHANGE_TIBIA_CONFIG 125
#define ERROR_CHANGE_TIBIA_HOST 126
#define ERROR_FIND_TIBIA_WINDOW 127
#define ERROR_WAIT_TIBIA_WINDOW 128
#define ERROR_THREAD_WAITER 129

#define MESSAGE_PROXY 130

#define MESSAGE_END_VIDEO 200
#define MESSAGE_EDIT_START 201
#define MESSAGE_EDIT_END 202
#define MESSAGE_EDIT_FAST 203
#define MESSAGE_EDIT_SLOW 204
#define MESSAGE_EDIT_SKIP 205
#define MESSAGE_EDIT_DELAY 206

#define ERROR_CREATE_SOCKET 207
#define ERROR_OLD_TIBIA 208
#define ERROR_FIND_HOST 209
#define ERROR_CONNECT_HOST 210
#define ERROR_CORRUPT_DATA 211
#define ERROR_OTSERVER_UPDATE 212
#define ERROR_NOT_WAIT 213
#define ERROR_NO_VIDEO 214
#define ERROR_RECONNECT 215
